name: Zaid Haque
favicon: null
layout_spectrum: 0.5483321791980416
typography_spectrum: 0.728172856150195
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9059567232616246
  lightness: 0.5327958399429917
  saturation: 0.945053823525086
  rhythmicContrast: 0.10386216873303056
purpose: []
