favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.945053823525086
  brandStrength: 0.2455197
  lightness: 0.5327958399429917
  brandColors:
    - '#2F2F31'
    - '#E9E9F1'
    - '#B3A491'
    - '#75706D'
    - '#AC302F'
  rhythmicContrast: 0.1038621687330306
typography_spectrum: 0.5215054
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
name: Zaid Haque
