name: Zaid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64944
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F2F31'
    - '#E9E9F1'
    - '#B3A491'
    - '#75706D'
    - '#AC302F'
  brandStrength: 0.2455197
  lightness: 0.5327958399429917
  saturation: 0.945053823525086
  rhythmicContrast: 0.1038621687330306
purpose: []
